server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders:                                 # rabbitmq 服务信息；
        defaultRabbit:                         # 定义名称，用于 binding 整合
          type: rabbit                         # 消息组件类型
          environment:                         # rabbitmq 相关的环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:                                # 服务的整合处理
        output:                                # 通道名称
          destination: providerExchange        # Exchange名称
          content-type: application/json       # 消息类型，json为 "application/json"，文本则为 "text/plain"
          binder: defaultRabbit                # 设置要绑定的消息服务

eureka:
  client:                                      # Eureka 注册配置
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 30      # 心跳时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 90   # 心跳超时时间（默认是90秒）
    instance-id: send-8801.com                 # 显示主机名称
    prefer-ip-address: true                    # 访问路径变为 IP 地址






