server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包 com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.56.117:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=True
    username: root
    password: 1123581321345589

eureka:
  client:
    # 是否注册 Eureka Server
    register-with-eureka: true
    # 是否从 Eureka Server 抓取已有的注册信息 集群模式下必须设置为 true 配合 ribbon 使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: org.droplet.springcloud.entities    # 所有Entity别名类所在包